### ISSUE TITLE
Build in tracker of the locations of busses and trains

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [grote/Transportr#746]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [X] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [X] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
This is not a request related to a problem.

**Describe the solution you'd like**
Hi is it possible to implement something like this NS and 9292 in the netherlands?

https://tracker.geops.ch/?z=14&s=1&x=642835.4788&y=6767597.5469&l=transport

It keeps track of the exact location of busses and trains.

**Describe alternatives you've considered**
-

**Additional context**
-
